# Base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY ./frontend /app/frontend

# Expose port and run application
EXPOSE 8501
CMD ["streamlit", "run", "frontend/app.py"]
